# Generated by Django 4.2.7 on 2023-12-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_transaction_remove_customer_ordered_products_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
